### default env
# ENV SERVER_ADDR     0.0.0.0
# ENV SERVER_PORT     51348
# ENV PASSWORD        psw
# ENV METHOD          aes-128-ctr
# ENV PROTOCOL        auth_aes128_md5
# ENV PROTOCOLPARAM   32
# ENV OBFS            tls1.2_ticket_auth_compatible
# ENV TIMEOUT         300
# ENV DNS_ADDR        8.8.8.8
# ENV DNS_ADDR_2      8.8.4.4
version: '3'
services:
  ssserver:
    image: breakwa11/shadowsocksr
    environment:
      - PASSWORD=test123
    ports:
      - 51348:51348